# Generated by Django 4.1.1 on 2022-09-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='CompanyOneTimeLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('is_active', models.BooleanField(default=True)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('odiuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=50, null=True)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.odiuser',),
        ),
    ]
